FROM debian:bullseye

ARG TAGOCORE_VERSION
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ARG NODE_VERSION=10.24.1

RUN echo "I am running on $BUILDPLATFORM, building v$TAGOCORE_VERSION for $TARGETPLATFORM" > /lo

RUN apt-get update && apt-get install -y curl libatomic1

WORKDIR /

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
RUN echo 'export NVM_DIR="$HOME/.nvm"'                                       >> "$HOME/.bashrc"
RUN echo '[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm' >> "$HOME/.bashrc"
RUN echo '[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion" # This loads nvm bash_completion' >> "$HOME/.bashrc"
RUN bash -c 'source $HOME/.nvm/nvm.sh && nvm install $NODE_VERSION && nvm use $NODE_VERSION && nvm alias default $NODE_VERSION'

RUN case $TARGETPLATFORM in "linux/arm64") curl -o tagocore.tar.gz https://downloads.tagocore.com/v${TAGOCORE_VERSION}/tagocore-v${TAGOCORE_VERSION}-linux-arm64.tar.gz ;; esac
RUN case $TARGETPLATFORM in "linux/amd64") curl -o tagocore.tar.gz https://downloads.tagocore.com/v${TAGOCORE_VERSION}/tagocore-v${TAGOCORE_VERSION}-linux-x64.tar.gz ;; esac
RUN case $TARGETPLATFORM in "linux/arm/v7") curl -o tagocore.tar.gz https://downloads.tagocore.com/v${TAGOCORE_VERSION}/tagocore-v${TAGOCORE_VERSION}-linux-armv7.tar.gz ;; esac
RUN npm install @tago-io/sdk

RUN tar -xvzf tagocore.tar.gz
RUN mv tagocore /usr/bin
RUN rm -rf tagocore.tar.gz

EXPOSE 8888/tcp
EXPOSE 8999/tcp
EXPOSE 1883/tcp

ENTRYPOINT [ "tagocore" ]
CMD [ "start", "--no-daemon" ]